-- MySQL Script generated by MySQL Workbench
-- Sun May 21 22:23:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DbGoogle
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DbGoogle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DbGoogle` DEFAULT CHARACTER SET utf8 ;
USE `DbGoogle` ;

-- -----------------------------------------------------
-- Table `DbGoogle`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DbGoogle`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `funcionarioNome` VARCHAR(45) NOT NULL,
  `funcionarioEmail` VARCHAR(45) NOT NULL,
  `fucnionarioIdade` INT NOT NULL,
  `funcionarioCargo` VARCHAR(45) NOT NULL,
  `funcionarioUnidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbGoogle`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DbGoogle`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuarioNome` VARCHAR(45) NOT NULL,
  `usuarioEmail` VARCHAR(45) NOT NULL,
  `usuarioIdade` INT NOT NULL,
  `usuarioSenha` VARCHAR(45) NOT NULL,
  `usuarioCelular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbGoogle`.`Cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DbGoogle`.`Cargos` (
  `idCargos` INT NOT NULL AUTO_INCREMENT,
  `cargoNome` VARCHAR(45) NOT NULL,
  `cargoSalario` FLOAT NOT NULL,
  `cargoHierarquia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbGoogle`.`Unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DbGoogle`.`Unidade` (
  `idUnidade` INT NOT NULL AUTO_INCREMENT,
  `unidadeNome` VARCHAR(45) NOT NULL,
  `unidadeEstado` VARCHAR(45) NOT NULL,
  `unidadePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUnidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbGoogle`.`App`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DbGoogle`.`App` (
  `idApp` INT NOT NULL AUTO_INCREMENT,
  `appNome` VARCHAR(45) NOT NULL,
  `appTamanho` VARCHAR(45) NOT NULL,
  `appNumDowload` INT NOT NULL,
  `appAvaliacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idApp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbGoogle`.`Servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DbGoogle`.`Servicos` (
  `idServicos` INT NOT NULL AUTO_INCREMENT,
  `servicoNome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idServicos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
